### ISSUE TITLE
Migrate CI to GitHub Actions

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux#2944]
Tasks:
- [x] unit tests #2940
- [x] codegen #2940
- [x] binaries and containers builds #2940
- [x] end-to-end testing #2940
- [x] release helm charts #3085
- [x] pre-release container images
- [x] release binaries upload
- [x] release container images
- [ ] run CVE scan on release

**Comment by kingdonb** [comment]
These issues all seem to be resolved, with the exception of CVE scanning which broke and had to be reverted. The scanning for CVEs is performed manually (with Snyk) between releases and for new releases.

Pre-release container images are published when the PR merges to master, and since the release cadence is likely going to be deliberately slowed down during maintenance, to minimize the effort required for downstreams, and before releases can be published, we will usually recommend folks who are still depending on Flux v1 to find the prerelease images here:

https://hub.docker.com/r/fluxcd/flux-prerelease/tags?page=1&ordering=last_updated

Closing out this issue.

**Comment by kingdonb** [comment]
Gack, I missed that some of these CI tasks that were left unchecked are still driven from CircleCI.

*  pre-release container images
* release binaries upload
* release container images

Let me know if I should reopen this issue. I don't think it is a high priority to resolve anymore, (Flux v1 will not be maintained forever, and was formally superseded by Flux v2 when the GitOps Toolkit API stability was announced about a month ago.)
